// <auto-generated />
using System;
using DevOIlApi.DBConnection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevOIlApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251016201706_migr")]
    partial class migr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevOIlApi.Models.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Comment");

                    b.Property<DateTime>("Date_of_bid")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Client")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Client");

                    b.Property<bool>("IsProcessedByAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("IsChecked");

                    b.HasKey("Id");

                    b.HasIndex("Id_Client");

                    b.ToTable("Bids", (string)null);
                });

            modelBuilder.Entity("DevOIlApi.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date_of_registration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Date_of_registration");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasAnnotation("EmailAddress", true);

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("First_Name");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Last_Name");

                    b.Property<string>("Phone_Number")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Phone_Number");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone_Number")
                        .IsUnique();

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("DevOIlApi.Models.Bid", b =>
                {
                    b.HasOne("DevOIlApi.Models.Client", "Client")
                        .WithMany("ClientBids")
                        .HasForeignKey("Id_Client")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("DevOIlApi.Models.Client", b =>
                {
                    b.Navigation("ClientBids");
                });
#pragma warning restore 612, 618
        }
    }
}
